#This is a sample Image 
FROM ubuntu 
MAINTAINER demousr@gmail.com
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
RUN apt-get update 
RUN apt-get install sudo -y
RUN sudo -E apt-get clean

COPY . .
CMD [“echo”,”Image created”,"/bin/bash/"] 
